### ISSUE TITLE
react-native init

### ISSUE THREAD

**Issue by grabbou** [rnpm/rnpm#10]
It'd be really cool to provide `npm init` like command, that when called `rnpm init`, just uses `react-native init` to scaffold a new project for user. Simple & easy.

**Comment by mkonicek** [comment]
Possibly related to `react-native new-library`?

**Comment by grabbou** [comment]
Is there such command already @mkonicek ? If not, I'd like to incorporate as much of local-cli as possible, esp. given the fact that we are bringing plugins system and this will be trivial to write/wrap.

**Comment by sospartan** [comment]
Updates? @grabbou   
Does this 'new-library'  with react-native or rnpm ?

**Comment by Kureev** [comment]
@sospartan 
```
➜  Basic git:(master) react-native
Usage: react-native <command>

Commands:
  - start: starts the webserver
  - bundle: builds the javascript bundle for offline use
  - new-library: generates a native library bridge
  - android: generates an Android project for your app
  - run-android: builds your app and starts it on a connected Android emulator or device
  - upgrade: upgrade your app's template files to the latest version; run this after updating the react-native version in your package.json and running npm install
```
